services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  ALLURE_OUTPUT_PATH: "/builds/via21u815/test-2024"
  CI: 1

stages:
  - unit-test
  - integration-test
  
unit:
  stage: unit-test
  image: sbtscala/scala-sbt:eclipse-temurin-alpine-22_36_1.10.2_3.5.1
  script: 
    - echo UNIT_SUCCESS=0 | tee >> $GITLAB_ENV
    - export UNIT_SUCCESS=0
    - printenv
    - sbt tests/test
    - echo UNIT_SUCCESS=1 | tee >> $GITLAB_ENV
  rules:
    - when: always
  allow_failure: true

integration:
  stage: integration-test
  image: sbtscala/scala-sbt:eclipse-temurin-alpine-22_36_1.10.2_3.5.1
  script: 
    - echo INTEGRATION_SUCCESS=0 | tee >> $GITLAB_ENV
    - export INTEGRATION_SUCCESS=0
    - printenv
    - sbt it/test
    - echo INTEGRATION_SUCCESS=1 | tee >> $GITLAB_ENV
  rules:
    - when: always
  allow_failure: true
