services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  TESTCONTAINERS_HOST_OVERRIDE: "host.docker.internal"
  ALLURE_OUTPUT_PATH: "/builds/via21u815/test-2024"


stages:
  # - unit-test
  # - integration-test
  - e2e-test
  - report 
  
# unit:
#   stage: unit-test
#   image: sbtscala/scala-sbt:eclipse-temurin-alpine-22_36_1.10.2_3.5.1
#   script: 
#     - echo UNIT_SUCCESS=0 | tee >> $GITLAB_ENV
#     - export UNIT_SUCCESS=0
#     - printenv
#     - sbt tests/test
#     - echo UNIT_SUCCESS=1 | tee >> $GITLAB_ENV
#   artifacts:
#     when: always
#     paths:
#       - modules/tests/target/test-reports
#   rules:
#     - when: always
#   allow_failure: true

# integration:
#   stage: integration-test
#   image: sbtscala/scala-sbt:eclipse-temurin-alpine-22_36_1.10.2_3.5.1
#   script: 
#     - echo INTEGRATION_SUCCESS=0 | tee >> $GITLAB_ENV
#     - export INTEGRATION_SUCCESS=0
#     - printenv
#     - sbt it/test
#     - echo INTEGRATION_SUCCESS=1 | tee >> $GITLAB_ENV
#   artifacts:
#     when: always
#     paths:
#       - modules/it/target/test-reports
#   rules:
#     - when: always
#   allow_failure: true

e2e:
  stage: e2e-test
  image: sbtscala/scala-sbt:eclipse-temurin-alpine-22_36_1.10.2_3.5.1
  script: 
    - apk add docker-compose
    - sbt e2e/test
  artifacts:
    when: always
    paths:
      - modules/e2e/target/test-reports
  rules:
    - when: always
  allow_failure: true

report:
  stage: report
  image: frankescobar/allure-docker-service:latest
  script: 
    - apt-get update && apt-get install unzip
    - mkdir allure-results 
    - echo $CI_COMMIT_BRANCH
    - echo $REPORT_TOKEN
    - 'curl --header "PRIVATE-TOKEN: $REPORT_TOKEN" --location "https://git.iu7.bmstu.ru/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_COMMIT_BRANCH/download?job=report" --output artifacts.zip' 
    - unzip artifacts.zip
    - cp -r ./allure-report/history ./allure-results
    - cp modules/tests/target/test-reports/* allure-results
    - cp modules/it/target/test-reports/* allure-results
    - cp modules/e2e/target/test-reports/* allure-results
    - allure generate allure-results -o allure-report
  artifacts:
    paths:
      - allure-report
  rules:
    - when: always
  allow_failure: true