openapi: 3.0.3
info:
  title: maweituo
  version: 1.0.0

tags:
  - name: auth
    description: Authorization
  - name: users
    description: Actions with users
  - name: ads
    description: Actions with advertisements
  - name: feed
    description: Actions with feed

paths:
  /login:
    post:
      tags:
        - auth
      summary: Login
      description: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "400":
          description: Bad request
        "403":
          description: Wrong password
        "500":
          description: Internal server error

  /register:
    post:
      tags:
        - auth
      summary: Register
      description: Register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
        "400":
          description: Bad request
        "409":
          description: Name/email taken
        "500":
          description: Internal server error

  /logout:
    post:
      tags:
        - auth
      summary: Logout
      security:
        - bearerAuth: []
      responses:
        "204":
          description: OK
        "500":
          description: Internal server error

  /tags:
    get:
      tags:
        - ads
      summary: get all tags
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AllTagsResponse"
        "500":
          description: Internal server error

  /tags/{tag}/ads:
    get:
      tags:
        - ads
      summary: get ads with tag
      parameters:
        - description: tag
          in: path
          name: tag
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagAdsResponse"
        "500":
          description: Internal server error

  /feed:
    get:
      tags:
        - feed
      summary: get public feed
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: number
        - name: pageSize
          in: query
          required: false
          schema:
            type: number
        - name: order
          in: query
          required: false
          schema:
            type: string
        - name: tags
          in: query
          required: false
          schema:
            type: string
        - name: title
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedResponse"
        "400":
          description: Bad request 
        "500":
          description: Internal server error
          
  /feed/{user}:
    get:
      tags:
        - feed
      summary: get user feed
      security:
        - bearerAuth: []
      parameters:
        - name: user 
          description: user id
          in: path 
          required: true 
          schema:
            type: string 
        - name: page
          in: query
          required: true
          schema:
            type: number
        - name: pageSize
          in: query
          required: false
          schema:
            type: number
        - name: order
          in: query
          required: false
          schema:
            type: string
        - name: tags
          in: query
          required: false
          schema:
            type: string
        - name: title
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeedResponse"
        "400":
          description: Bad request 
        "403":
          description: Forbidden
        "500":
          description: Internal server error
  
  /users/{user}:
    get:
      tags: 
        - users
      summary: get user information
      parameters:
        - name: user 
          description: user id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPublicInfo"
        "500":
          description: Internal server error      
    delete:
      tags: 
        - users
      summary: delete user 
      security:
        - bearerAuth: []
      parameters:
        - name: user 
          description: user id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: OK 
        "500":
          description: Internal server error      
          
    put:
      tags: 
        - users
      summary: update user 
      security:
        - bearerAuth: []
      parameters:
        - name: user 
          description: user id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserRequest"
      responses:
        "204":
          description: OK 
        "500":
          description: Internal server error      
          
  /users/{user}/ads:
    get:
      tags: 
        - users
      summary: get user ads
      parameters:
        - name: user 
          description: user id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAdsResponse"
        "500":
          description: Internal server error
          
  /ads:
    post:
      tags:
        - ads 
      summary: creat ad
      parameters:
        - name: ad 
          description: ad id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateAdRequest"
      responses:
        "204":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateAdResponse"
        "500":
          description: Internal server error
      
        
  /ads/{ad}:
    get: 
      tags:
        - ads 
      summary: get ad info 
      parameters:
        - name: ad 
          description: ad id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdResponse"
        "500":
          description: Internal server error
    put: 
      tags:
        - ads 
      summary: update ad info 
      security:
        - bearerAuth: []
      parameters:
        - name: ad 
          description: ad id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAdRequest"
      responses:
        "204":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdResponse"
        "403": 
          description: Forbidden
        "500":
          description: Internal server error
    delete: 
      tags:
        - ads 
      summary: delete ad
      security:
        - bearerAuth: []
      parameters:
        - name: ad 
          description: ad id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: OK
        "403": 
          description: Forbidden
        "500":
          description: Internal server error
          
  /ads/{adId}/imgs:
    post: 
      tags:
        - ads 
      summary: upload image
      parameters:
        - name: adId
          description: ad id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "204":
          description: OK
        "500":
          description: Internal server error
          
  /ads/{adId}/imgs/{imgId}:
    get: 
      tags:
        - ads 
      summary: get image
      parameters:
        - name: adId
          description: ad id
          in: path
          required: true
          schema:
            type: string
        - name: imgId
          description: ad id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "500":
          description: Internal server error
    delete: 
      tags:
        - ads 
      summary: delete image
      security:
        - bearerAuth: []
      parameters:
        - name: adId
          description: ad id
          in: path
          required: true
          schema:
            type: string
        - name: imgId
          description: ad id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: OK
        "403":
          description: Unauthorized
        "500":
          description: Internal server error
          
  /ads/{adId}/tags:
    get:
      tags:
        - ads 
      summary: get tags
      parameters:
        - name: adId
          description: ad id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdTagsResponse"
        "403":
          description: Unauthorized
        "500":
          description: Internal server error
    post:
      tags:
        - ads 
      summary: add tag 
      security:
        - bearerAuth: []
      parameters:
        - name: adId
          description: ad id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddTagRequest"
      responses:
        "204":
          description: OK
        "403":
          description: Unauthorized
        "500":
          description: Internal server error
    
    delete:
      tags:
        - ads 
      summary: delete tag 
      security:
        - bearerAuth: []
      parameters:
        - name: adId
          description: ad id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteTagRequest"
      responses:
        "204":
          description: OK
        "403":
          description: Unauthorized
        "500":
          description: Internal server error
  
  /ads/{adId}/msg/{chatId}: 
    get:
      tags:
        - ads 
      summary: get chat history
      parameters:
        - name: chatId
          description: chat id
          in: path
          required: true
          schema:
            type: string
        - name: adId
          description: ad id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HistoryResponse"
        "403":
          description: Unauthorized
        "500":
          description: Internal server error
    post:
      tags:
        - ads 
      summary: send message 
      security:
        - bearerAuth: []
      parameters:
        - name: chatId
          description: ad id
          in: path
          required: true
          schema:
            type: string
        - name: adId
          description: ad id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageRequest"
      responses:
        "204":
          description: OK
        "403":
          description: Unauthorized
        "500":
          description: Internal server error
  
  
  /ads/{adId}/chats/{chatId}:
    post:
      tags:
        - ads 
      summary: get chat 
      security:
        - bearerAuth: []
      parameters:
        - name: chatId
          description: chat id
          in: path
          required: true
          schema:
            type: string
        - name: adId
          description: ad id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chat"
        "403":
          description: Unauthorized
        "500":
          description: Internal server error
  
  /ads/{adId}/chats:
    post:
      tags:
        - ads 
      summary: create chat 
      security:
        - bearerAuth: []
      parameters:
        - name: adId
          description: ad id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageRequest"
      responses:
        "204":
          description: OK
        "403":
          description: Unauthorized
        "500":
          description: Internal server error
        

components:
  schemas:
    Pagination:
      type: object
      properties:
        pageSize:
          type: number
        page:
          type: number

    FeedResponse:
      type: object
      properties:
        items:
          items:
            type: string
          type: array
        pag:
          $ref: "#/components/schemas/Pagination"
        totalPages:
          type: number
        totalItems:
          type: number

    LoginRequest:
      type: object
      properties:
        name:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        jwt:
          type: string

    RegisterRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string

    RegisterResponse:
      type: object
      properties:
        user:
          type: string

    UpdateUserRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
          
    UpdateAdRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        resolved: 
          type: boolean
        title:  
          type: string

    UserPublicInfo:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string

    UserAdsResponse:
      type: object
      properties:
        userId:
          type: string
        ads:
          items:
            type: string
          type: array

    AdTagsResponse:
      type: object
      properties:
        adId:
          type: string
        tags:
          items:
            type: string
          type: array

    AddTagRequest:
      type: object
      properties:
        tag:
          type: string

    DeleteTagRequest:
      type: object
      properties:
        tag:
          type: string

    AdResponse:
      type: object
      properties:
        id:
          type: string
        authorId:
          type: string
        title:
          type: string
        resolved:
          type: string

    CreateAdRequest:
      type: object
      properties:
        title:
          type: string

    CreateAdResponse:
      type: object
      properties:
        id:
          type: string

    MarkAdResolvedRequest:
      type: object
      properties:
        withWhom:
          type: string

    Message:
      type: object
      properties:
        senderId:
          type: string
        chatId:
          type: string
        text:
          type: string
        at:
          type: string

    HistoryResponse:
      type: object
      properties:
        chatId:
          type: string
        messages:
          items:
            $ref: "#/components/schemas/Message"
          type: array

    SendMessageRequest:
      type: object
      properties:
        text:
          type: string

    Chat:
      type: object
      properties:
        id:
          type: string
        adId:
          type: string
        adAuthor:
          type: string
        clientId:
          type: string

    AllTagsResponse:
      type: object
      properties:
        tags:
          items:
            type: string
          type: array

    TagAdsResponse:
      type: object
      properties:
        tag:
          type: string
        adIds:
          items:
            type: string
          type: string
