global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'core'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['core:8080']
      
  - job_name: 'core-zio'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['core-zio:8080']