{
 "title": "http4s Sample Dashboard",
 "description": "Simple sample dashboard for some of the default metrics exported by the http4s-prometheus-metrics",
 "tags": [
  "JVM",
  "prometheus",
  "http4s"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(server_response_duration_seconds_bucket{instance=\"core-zio:8080\"}[10s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(server_response_duration_seconds_bucket{instance=\"core-zio:8080\"}[10s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(server_response_duration_seconds_bucket{instance=\"core-zio:8080\"}[10s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(server_response_duration_seconds_bucket{instance=\"core-zio:8080\"}[10s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(server_response_duration_seconds_bucket{instance=\"core-zio:8080\"}[10s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(server_response_duration_seconds_bucket{instance=\"core:8080\"}[10s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(server_response_duration_seconds_bucket{instance=\"core:8080\"}[10s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(server_response_duration_seconds_bucket{instance=\"core:8080\"}[10s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(server_response_duration_seconds_bucket{instance=\"core:8080\"}[10s])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(server_response_duration_seconds_bucket{instance=\"core:8080\"}[10s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "server_response_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "http4s Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Total Requests by Http Method and Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    { "expr": "server_request_count_total" }
   ]
  },
  {
   "title": "Server Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(server_active_request_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Duration (seconds)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(server_response_duration_seconds_bucket) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Jvm Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Memory used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_bytes_used", "legendFormat": "{{area}} memory [{{instance}}]" }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "current [{{instance}}]" },
    { "expr": "jvm_threads_daemon", "legendFormat": "daemon [{{instance}}]" }
   ]
  },
  {
   "title": "Class loading",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_classes_loaded", "legendFormat": "loaded [{{instance}}]" }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  }
 ]
}