POST http://localhost:8080/login
Content-Type: application/json

{
    "name": "maweituo",
    "password": "maweituo"
}

###
POST http://localhost:8080/register
Content-Type: application/json

{
    "name": "maweituo",
    "email": "maweituo@maweituo.com",
    "password": "maweituo"
}


